export const FETCH_DETAIL_ADD_IN_SITE_DONE = 'FETCH_DETAIL_ADD_IN_SITE_DONE'
export const FETCH_DETAIL_ADD_IN_SITE_DOING = 'FETCH_DETAIL_ADD_IN_SITE_DOING'

export const FETCH_DETAIL_CANCEL_IN_ARTICLE_DONE = 'FETCH_DETAIL_CANCEL_IN_ARTICLE_DONE'
export const FETCH_DETAIL_CANCEL_IN_ARTICLE_DOING = 'FETCH_DETAIL_CANCEL_IN_ARTICLE_DOING'

