export const FETCH_ADD_IN_SITE_DONE = 'FETCH_ADD_IN_SITE_DONE'
export const FETCH_ADD_OUT_SITE_DONE = 'FETCH_ADD_OUT_SITE_DONE'

export const FETCH_CANCEL_IN_ARTICLE_DONE = 'FETCH_CANCEL_IN_ARTICLE_DONE'
export const FETCH_CANCEL_IN_MY_DONE = 'FETCH_CANCEL_IN_MY_DONE'
