export const FETCH_HOME_LIST_DOING = 'FETCH_HOME_LIST_DOING';
export const FETCH_HOME_LIST_DONE = 'FETCH_HOME_LIST_DONE';
export const FETCH_HOME_LIST_ERROR = 'FETCH_HOME_LIST_ERROR';

export const FETCH_HOME_BANNER_DONE = 'FETCH_HOME_BANNER_DONE'

export const FETCH_HOME_ADD_IN_SITE_DONE = 'FETCH_HOME_ADD_IN_SITE_DONE'


export const FETCH_HOME_CANCEL_IN_ARTICLE_DONE = 'FETCH_HOME_CANCEL_IN_ARTICLE_DONE'

export const CHANGE_HOME_LIKE_ACTION = 'CHANGE_HOME_LIKE_ACTION'
