export const FETCH_HOME_LIST_DOING = 'FETCH_HOME_LIST_DOING';
export const FETCH_HOME_LIST_DONE = 'FETCH_HOME_LIST_DONE';
export const FETCH_HOME_LIST_ERROR = 'FETCH_HOME_LIST_ERROR';

export const FETCH_HOME_BANNER_DONE = 'FETCH_HOME_BANNER_DONE'
