export const FETCH_LIKE_DONE = 'FETCH_LIKE_DONE'
export const FETCH_LIKE_DOING = 'FETCH_LIKE_DOING'
export const FETCH_LIKE_ERROR = 'FETCH_LIKE_ERROR'

export const FETCH_LIKE_CANCEL_IN_MY_DONE = 'FETCH_LIKE_CANCEL_IN_MY_DONE'
