export const FETCH_PROJECT_LIST_DONE = 'FETCH_PROJECT_LIST_DONE'
export const FETCH_PROJECT_LIST_DOING = 'FETCH_PROJECT_LIST_DOING'

export const FETCH_PEOJECT_ADD_IN_SITE_DONE = 'FETCH_PEOJECT_ADD_IN_SITE_DONE'
export const FETCH_PEOJECT_ADD_IN_SITE_DOING = 'FETCH_PEOJECT_ADD_IN_SITE_DOING'
export const FETCH_PEOJECT_ADD_IN_SITE_ERROR = 'FETCH_PEOJECT_ADD_IN_SITE_ERROR'

export const FETCH_PROJECT_CANCEL_IN_ARTICLE_DONE = 'FETCH_PROJECT_CANCEL_IN_ARTICLE_DONE'

export const CHANGE_LIKE_ACTION = 'CHANGE_LIKE_ACTION'