export const FETCH_PROJECT_LIST_DONE = 'FETCH_PROJECT_LIST_DONE'
export const CHANGE_ICON = 'CHANGE_ICON'

export const FETCH_PEOJECT_ADD_IN_SITE_DONE = 'FETCH_PEOJECT_ADD_IN_SITE_DONE'
export const FETCH_PEOJECT_ADD_IN_SITE_DOING = 'FETCH_PEOJECT_ADD_IN_SITE_DOING'
export const FETCH_PEOJECT_ADD_IN_SITE_ERROR = 'FETCH_PEOJECT_ADD_IN_SITE_ERROR'