export const FETCH_SYSTEM_LIST_DONE = 'FETCH_SYSTEM_LIST_DONE'
export const FETCH_SYSTEM_LIST_DOING = 'FETCH_SYSTEM_LIST_DOING'


export const FETCH_SYSTEM_DETAIL_LIST_DONE = 'FETCH_SYSTEM_DETAIL_LIST_DONE'
export const FETCH_SYSTEM_DETAIL_LIST_DOING = 'FETCH_SYSTEM_DETAIL_LIST_DOING'

export const FETCH_SYSTEM_ADD_IN_SITE_DONE = 'FETCH_SYSTEM_ADD_IN_SITE_DONE'


export const FETCH_SYSTEM_CANCEL_IN_ARTICLE_DONE = 'FETCH_SYSTEM_CANCEL_IN_ARTICLE_DONE'