export const FETCH_LOGIN_DONE = 'FETCH_LOGIN_DONE'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'
export const FETCH_LOGIN_DOING = 'FETCH_LOGIN_DOING'

export const FETCH_ISLOGIN_DONE = 'FETCH_ISLOGIN_DONE'
export const FETCH_ISLOGIN_ERROE = 'FETCH_ISLOGIN_ERROE'

export const FETCH_REGISTER_DONE = 'FETCH_REGISTER_DONE'
export const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR'
export const FETCH_REGISTER_DOING = 'FETCH_REGISTER_DOING'