export const FETCH_LOGIN_DONE = 'FETCH_LOGIN_DONE'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'


export const FETCH_REGISTER_DONE = 'FETCH_REGISTER_DONE'
export const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR'
